name: Codecov
on: pull_request
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch
        uses: actions/checkout@master
      - name: Test
        run: phpunit --coverage-html build/coverage-report --configuration phpunit.xml --coverage-clover=coverage.xml
      - name: Upload
        uses: codecov/codecov-action@v1
        with:
          files: ./tests
          token: 2765af24-3ab9-4f3b-863c-b1c04d60f582'
