name: Codecov
on: pull_request
jobs:
  code-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v2
        with:
          args: --no-interaction --no-progress
      - name: Test
        run: phpunit --coverage-html build/coverage-report --configuration phpunit.xml --coverage-clover=coverage.xml
      - name: Upload
        uses: codecov/codecov-action@v1
        with:
          files: tests
          token: 2765af24-3ab9-4f3b-863c-b1c04d60f582
