name: PHPunit
on: pull_request
jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: pxgamer/phpunit-action@master
        with:
          bootstrap: vendor/autoload.php
            configuration: phpunit.xml
